name: deploy

on:
  push:
    branches: [main] # master 分支有 push 时触发
    paths-ignore:    # 下列文件的变更不触发部署，可以自行添加
      - README.md

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # 部署到 GitHub pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3 # 使用部署到 GitHub pages 的 action
        with:
          external_repository: BioITee/BioITAssets
          personal_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages	# 发布到哪个 branch
          force_orphan: true
          full_commit_message: ${{ github.event.head_commit.message }}
          cname: 'assets.bioitee.com'
